# logging ?? ??
logging:
  level:
    root: INFO
    sql: ERROR
# Overloaded POST ??
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
# session
server:
  servlet:
    session:
      timeout: 10m # ??? 30??? ??? 1????.
